apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dotnet-app
  namespace: dotnet-app          
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm/dotnet-app
      sourceRef:
        kind: GitRepository
        name: dotnet-app
        namespace: flux-system
  values:
    replicaCount: 3
    image:
      tag: v1
